return {
  bash = "sh",
  c = "c",
  cpp = "cpp",
  css = "css",
  dot = "dot",
  elixir = "ex",
  go = "go",
  haskell = "hs",
  html = "html",
  javascript = "js",
  julia = "jl",
  lua = "lua",
  markdown = "md",
  nix = "nix",
  php = "php",
  python = "py",
  r = "R",
  ruby = "rb",
  rust = "rs",
  sql = "sql",
  typescript = "ts",
  typst = "typ",
  yaml = "yml",
}
