return {
  bash = "sh",
  css = "css",
  dot = "dot",
  elixir = "ex",
  haskell = "hs",
  html = "html",
  javascript = "js",
  julia = "jl",
  lua = "lua",
  markdown = "md",
  typst = "typ",
  python = "py",
  r = "R",
  rust = "rs",
  sql = "sql",
  yaml = "yml",
}
